; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s2-saola-1]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF53
;platform = espressif32
board = esp32-s2-saola-1
framework = arduino
; This line tells PlatformIO to free more room for non-vol storage
board_build.partitions = morenvsflash.csv
board_build.flash_size = 4MB
; The ESP32‑S2 brownout detector is very sensitive. ✔ Fix: Raise or disable brownout threshold
build_flags = -D DISABLE_BROWNOUT